#
# Azure Pipelines job for building and testing create-react-app on Linux, Windows, and macOS.
#

parameters:
  name: ''
  testScript: ''
  configurations:
    LinuxNode14: { vmImage: 'ubuntu-latest', nodeVersion: 14.x }
    LinuxNode16: { vmImage: 'ubuntu-latest', nodeVersion: 16.x }

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.configurations }}
    pool:
      vmImage: $(vmImage)
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global user.name "Create React App"
          git config --global user.email "cra@email.com"
        displayName: 'Initialize Git config'

      - checkout: self
        path: create-react-app

      - task: NodeTool@0
        inputs:
          versionSpec: $(nodeVersion)
        displayName: 'Install Node.js'

      - script: yarn --frozen-lockfile
        displayName: 'Run yarn'

      - bash: ${{ parameters.testScript }}
        displayName: 'Run tests'
